import { resolve } from 'node:path';
import { defineConfig } from 'vite';

// Static multi-language build: web/{en,es,pl,ru}/index.html are generated by
// web/scripts/gen-pages.mjs and share one JS/CSS bundle. Output: dist/.
export default defineConfig({
    root: 'web',
    publicDir: 'public',
    base: '/',
    build: {
        outDir: resolve(process.env.SOG_OUT || 'dist'),
        emptyOutDir: true,
        target: 'es2022',
        sourcemap: true,
        assetsInlineLimit: 0,
        chunkSizeWarningLimit: 4096,
        rollupOptions: {
            input: {
                root: resolve('web/index.html'),
                en: resolve('web/en/index.html'),
                es: resolve('web/es/index.html'),
                pl: resolve('web/pl/index.html'),
                ru: resolve('web/ru/index.html')
            }
        }
    },
    worker: {
        format: 'es'
    },
    optimizeDeps: {
        // keep the package's own import.meta.url-relative files (worker.mjs, webp.wasm) intact in dev
        exclude: ['@playcanvas/splat-transform']
    },
    server: {
        port: 5180,
        strictPort: true
    }
});
